---
title: 'FAIR'
teaching: 10
exercises: 1
---

:::::::::::::::::::::::::::::::::::::: questions 

- How can you make your research data more FAIR?
- What are the principles of CARE?
- How can you share your research data with principles?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Understand the principles of FAIR
- Understand the practical steps to implementing FAIR Principles

::::::::::::::::::::::::::::::::::::::::::::::::

## Introduction

FAIR (Findable, Accessible, Interoperable, and Re-usable) principles are designed to make research data more discoverable, both by humans and machines. FAIR principles can be applied to digital data from any discipline.

CARE (Collective benefit, Authority to control, Responsibility, and Ethics) principles are people and purpose-oriented and reflect the role of data in advancing indigenous innovation and self-determination. Throughout this section, we will go into detail about FAIR and CARE and provide some practical steps to apply these principles to your research data.

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor

This episode should be pretty straightforward. There may be questions around the practical implementations. CARE may only apply to certain types of research data, but it's important for the researchers to be aware that these exist.

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

## Why use FAIR principles
FAIR principles are headed by the [GO FAIR Initiative](https://www.go-fair.org/fair-principles/) and stand for

- **F**indable
- **A**ccessible
- **I**nteroperable
- **R**e-usable

### Benefits of FAIR
Working towards making research data more FAIR provides many benefits including:

- increasing the visibility and citations of your research
- improving the reproducibility and reliability of your research
- enabling  new innovative research approaches and tools
- aligning with international standards and approaches

## How do you make your research more FAIR
### Findable
To make research data findable, publish the data (or a metadata-only record) with as much research metadata as possible. Most research data publishing platforms provide you with a persistent identifier, such as a [Digital Object Identifier](https://www.doi.org/the-identifier/what-is-a-doi/), which you can use to cite or share you work.

### Accessible
To make your research data more accessible, ensure it can be downloaded over the internet from the publishing platform it is hosted on. As with the previous episode, this involves data with the proper "rawness" in order to reproduce results and the repository size should be as small as possible to facilitate download and storage. Consider using a publishing platform that supports API (Application Programming Interface) access to make it easier for machines and databases to harvest the research data or it's metadata.

### Interoperable
To make research data interoperable, use community-accepted languages, [formats](https://ardc.edu.au/resources/community-endorsed-data-standards/), and [vocabularies](https://ardc.edu.au/resource/vocabularies-and-research-data-2/) in the data and metadata. Metadata should reference and describe relationships to other data, metadata, and information through the use of [identifiers](https://ardc.edu.au/resources/working-with-data/citation-identifiers/).

### Re-usable
To make research data reusable, it should come with a clear human and machine-readable license and [provenance](https://rd-alliance.org/groups/research-data-provenance.html) information on how it was collected and generated. It should also abide by discipline-specific data and metadata standards where possible, to ensure it retains important context. The Data Management Plan, README file, and Dataset README file are all parts of making your data reusable.

::::::::::::::::::::::::::::::::::::: challenge 

## Making data FAIR
Thinking about your research data. What are some easy practical steps to make your data FAIR?

:::::::::::::::::::::::: solution 

- publish your research data in a publicly accessible repository when possible
- mint a persistent identifier for your research data
- use community accepted language in data and metadata
- specify the license and provenance for your research data.
- include metadata and README files.

:::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: keypoints 

- Following FAIR principles can make your research more visable, citable, and reproducible.
- Publish your data in a publicly accessible repository where you can get a persistent digital object identifier.

::::::::::::::::::::::::::::::::::::::::::::::::

[^1]: Global Indigenous Data Alliance. CARE Principles for Indigenous Data Governance. 2025. [https://www.gida-global.org/care](https://www.gida-global.org/care).

[^2]: Tahu Kukutai and John Taylor (Eds.). Indigenous Data Sovereignty: Toward an agenda. ANU Press, 2016. URL [http://www.jstor.org/stable/j.ctt1q1crgf](http://www.jstor.org/stable/j.ctt1q1crgf)

[^3]: The United Nations Declaration on the Rights of Indigenous Peoples. Sept. 2007. URL [UNDRIP](https://www.un.org/development/desa/indigenouspeoples/wp-content/uploads/sites/19/2018/11/UNDRIP_E_web.pdf)

[^4]: "IEEE Draft Recommended Practice for Provenance of Indigenous Peoples Data," in IEEE P2890/D1, November 2024 , vol., no., pp.1-24, 4 Dec. 2024. URL [https://ieeexplore.ieee.org/document/10780988](https://ieeexplore.ieee.org/servlet/opac?punumber=10780986)

[^5]: Jacob Prehn *et al*. (2023). “Indigenous Data Governance and Universities Communiqué.” Global Indigenous Data Alliance. URL [https://www.maiamnayriwingara.org/s/GIDA-Communique-2023.pdf](https://www.maiamnayriwingara.org/s/GIDA-Communique-2023.pdf).

[^6]: A tangible or intangible item or matter of special cultural significance.
